### ISSUE TITLE
no module named 'reader'

### ISSUE THREAD

**Issue by jajpater** [rwev/bible#1]
Traceback (most recent call last):
  File "/home/jajpater/.local/bin/bible", line 5, in <module>
    from bible.main import main
  File "/home/jajpater/.local/lib/python3.8/site-packages/bible/main.py", line 3, in <module>
    from reader import Reader
ModuleNotFoundError: No module named 'reader'

**Comment by jajpater** [comment]
When installing system wide, same problem: 
Traceback (most recent call last):
  File "/usr/local/bin/bible", line 11, in <module>
    load_entry_point('setup==0.1.0', 'console_scripts', 'bible')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jajpater/.local/lib/python3.8/site-packages/bible/main.py", line 3, in <module>
    from reader import Reader
ModuleNotFoundError: No module named 'reader'

**Comment by rwev** [comment]
Hi @jajpater, thanks for the feedback and interest. I'm happy you came to check it out!

I believe I fixed this issue - caused by changes to relative imports in python3 - in the latest commit. 

Please try installing again and let me know if it now works for you.

```
python3 -m pip uninstall bible
python3 -m pip install https://github.com/rwev/bible/archive/master.zip --no-cache-dir
```

**Comment by jajpater** [comment]
Thanks! It works! Only now I get another error when using the program. Should I open a new issue?

**Comment by rwev** [comment]
Please do open another issue!
