### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jman223** [rwev/bible#10]
I've installed according to your instructions (running on Arch Linux) and when I try to run the application I get the following:

> Traceback (most recent call last):
>   File "/home/jman223/.local/bin/bible", line 5, in <module>
>     from bible.main import main
>   File "/home/jman223/.local/lib/python3.9/site-packages/bible/main.py", line 6, in <module>
>     from textwrap2 import wrap
> ModuleNotFoundError: No module named 'textwrap2'

Suggestions?

**Comment by jman223** [comment]
I resolved this issue by making the following change to ~/.local/lib/python3.9/site-packages/bible/main.py

**Original**
`from textwrap2 import wrap`

**Modification**
`from hyphen.textwrap2 import wrap`
